name: giga_pelanggan
description: "Aplikasi pelanggan gigainternet.id untuk memudahkan pembayaran online."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  get: ^4.6.6
  http: ^1.2.2
  intl: ^0.20.1
 

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/1024.png
    - assets/icons/logo-landscape.png
